### ISSUE TITLE
join / merge with supabase_rs crate

### ISSUE THREAD

**Issue by floris-xlx** [supabase-community/supabase-auth-rs#10]
hey whatsup man

I just seen your crate, awesome work.

I maintain [supabase_rs](https://crates.io/crates/supabase_rs) which is the biggest supabase crate on there right now i believe.
there is no auth functionality added in there yet as of today, database & storage & graphql is in there however.

do you have a slack/discord/email where i can hit your messages? you could join us and we merge your auth-rs into it to make 1 complete sdk and we have a chance of being listed on supabase's website for recognized rust SDKs

discord=  floris_xlx
email = floris@xylex.ai

**Comment by Proziam** [comment]
I'm happy to collaborate! I reached out via email so we can pick this up there.
