### ISSUE TITLE
Add crate feature flags to use rustls-tls instead of native-tls in reqwest crate

### ISSUE THREAD

**Issue by jonatino** [supabase-community/supabase-auth-rs#11]
# Feature request

## Is your feature request related to a problem? Please describe.

Right now you use the reqwest crate with default features. By default it uses native-tls which is a bit of a pain to build for android since you need your own openssl dependency. Could you add features to this crate which allow us to use a rustls implementation for tls?

## Describe the solution you'd like

Eg (note the default-features=false since it's required to avoid the native-tls dependency in reqwest):
```rust
reqwest = { version = "0.12.9", default-features = false, features = ["rustls-tls"] }
```

**Comment by Proziam** [comment]
Apologies for the delayed response, the holiday season is upon us.

I'll look into it this week 👍

**Comment by Proziam** [comment]
Version 10.0.6 now has the `use-rustls` feature. I also discovered a discussion on Reqwest about [using rustls as the default](https://github.com/seanmonstar/reqwest/issues/2025) which I will start tracking.

Let me know if this works for you, and thanks for taking the time to open the issue!
